### ISSUE TITLE
Improve interface

### ISSUE THREAD

**Issue by cvsvensson** [williamesamuelson/AffineRayleighOptimization.jl#11]
Currently, one specifies a quadratic form or a rayleigh quotient for the left hand side and then a vector or Span for the right hand side. In principle, this is four different choices, but we don't support all of them.
Also, if one uses Rayleigh, then using a vector or a Span is equivalent right?

What if we only used a quaddratic form for the LHS, and let the user specify a vector or a Span on the RHS? Then we support all choices, and all choices are different.

**Comment by williamesamuelson** [comment]
I might be missing something (it's been a while since I thought about this) but I'm not sure I understand. I don't think a quadratic form with a span is something we want to solve. 

I agree that the RQ problem with a 1D span and a fixed vector are equivalent: if one can solve one of them, the other is easily solved. 

But I'm not sure I agree with

$$\min_x \quad x^\dagger Q x \quad \mathrm{s.t.} \quad Cx = \mathrm{Span}(b_1, ... ,b_n) $$
If n=1 this problem is equivalent to the Rayleigh Quotient problem 
$$\min_x \quad \frac{x^\dagger Q x}{x^\dagger x} \quad \mathrm{s.t.} \quad Cx = b $$

The first problem has a candidate $x' = 0$ so the minimum $x^\dagger Q x \leq 0$. If $Q$ is positive definite, this is the optimal solution. However, it's not compatible with the constraint in the second problem. Maybe if one adds $|x|=1$ to the first problem they are the same?

To me it seems like we support three kinds of problems.

1. Quadratic form with a fixed RHS constraint (QF_BACKSLASH)
2. RQ with a 1D fixed RHS constraint (equivalent with RQ with 1D span) (RQ_EIG, RQ_SPARSE, RQ_CHOL, RQ_GENEIG)
3. RQ with n>1 dim span RHS constraint (RQ_EIG)

**Comment by cvsvensson** [comment]
You're right. So I guess we should have two different problem types. I would propose to have:

- QuadraticProblem(Q, C, b)  (perhaps error if ndims(b)>1)
- RayleighProblem(Q, C, b)  (return solution such that Cx=b if ndims(b)=1 else if ndims(b) = 2  use a canonical normalizaton like |x|=1)

Then we could get rid of Span. How does this sound?

**Comment by williamesamuelson** [comment]
Yes, that sounds good!

With 

> else if ndims(b) = 2 use a canonical normalizaton like |x|=1)

do you mean "else if ndims(b) > 1 return solution such that $Cx\in \mathrm{Span}(b_1, ...,b_n)$"?

**Comment by cvsvensson** [comment]
ndims(b) > 2 doesn't make any sense. ndims(b) ==2 means that it's a matrix and we'll take the columns as the vectors. Otherwise yes I do mean that Cx =Span(b). But unless we need Span for dispatch, I think we can get rid of the struct.  It doesn't provide any other functionality really.

**Comment by williamesamuelson** [comment]
Ah, yes! I read it as the number of columns. 

I agree that we can remove Span!
